CREATE TABLE "onboarding"."agents" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_no" varchar(50) NOT NULL,
	"name" varchar(255) NOT NULL,
	"id_no" varchar(50) NOT NULL,
	"email_address" varchar(255) NOT NULL,
	"mobile_no" varchar(20) NOT NULL,
	"tel_no" varchar(20),
	"postal_address" varchar(255),
	"postal_code" varchar(20),
	"physical_address" text,
	"country" varchar(100),
	"city" varchar(100),
	"town" varchar(100),
	"status" varchar(20) DEFAULT '0' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"added_by" text NOT NULL,
	"confirmed" boolean DEFAULT false,
	"confirmed_by" text,
	"confirmed_at" timestamp,
	CONSTRAINT "agents_agent_no_unique" UNIQUE("agent_no"),
	CONSTRAINT "agents_id_no_unique" UNIQUE("id_no"),
	CONSTRAINT "agents_email_address_unique" UNIQUE("email_address"),
	CONSTRAINT "agents_mobile_no_unique" UNIQUE("mobile_no")
);
